### PR TITLE
Fix Highlighting Error

### PR DESCRIPTION
**Pull request by charles01pd2018**
There was issues with the custom functions used for highlighting, and I found out that prose-mirror commands provides a default toggleMark function.

Now, when highlights are applied it saves correctly to avoid applying spacing in-between and inner text content that is marked up.

### CODE REVIEW

**Comment by hadielyakhni** [comment]
hey @charles01pd2018 - does it happen on your end too? https://streamable.com/vokw8d
this issue was happening for different marks on my end, not just highlights

**Comment by charles01pd2018** [comment]
> hey @charles01pd2018 - does it happen on your end too? https://streamable.com/vokw8d this issue was happening for different marks on my end, not just highlights

: -(((((

So I learned that if there is a space in between marked text it doesn't render correctly. So if we bold a piece of text that already has a mark on it WITH that space, it gets messed up.

I'll keep working on this but markers won't produce the syntax error anymore.

**Comment by hadielyakhni** [comment]
> So I learned that if there is a space in between marked text it doesn't render correctly. So if we bold a piece of text that already has a mark on it WITH that space, it gets messed up.

so to clarify what i recorded: `a<space>` - the `a` was italic only (no bold involved), and the `<space>` was bold only (no italic involved) - so it's not necessarily for the 2 marks to be applied on the same character for the problem to happen

**Comment by charles01pd2018** [comment]
> https://streamable.com/vokw8d

hmmmmm ok this makes it more interesting!

**Comment by charles01pd2018** [comment]
ok i just fixed the error in the most recent commit I think - I had to look thru the source code to find there was like a hidden value that was labeled deprecated :-3

**Pull request merged**
