### PR TITLE
Add Paragraph Tabbing ability

### PR DESCRIPTION
**Pull request by charles01pd2018**
DOES NOT INCLUDE LIST TABBING DESCRIBED HERE:
https://streamable.com/lpl4mv

### CODE REVIEW

**Comment by Apandoh** [comment]
Hey @charles01pd2018 can you describe what this is adding - a bit confused. I saw the video on what it's not adding but is this just for indenting?

**Comment by charles01pd2018** [comment]
> Hey @charles01pd2018 can you describe what this is adding - a bit confused. I saw the video on what it's not adding but is this just for indenting?

this is just adding the ability to tab regular paragraphs -> so like in google docs when you hit tab it indents

**Comment by charles01pd2018** [comment]
> Hey @charles01pd2018 can you describe what this is adding - a bit confused. I saw the video on what it's not adding but is this just for indenting?

So it just inserts four spaces basically -> https://streamable.com/8joqc6

**Comment by Apandoh** [comment]
> > Hey @charles01pd2018 can you describe what this is adding - a bit confused. I saw the video on what it's not adding but is this just for indenting?
> 
> So it just inserts four spaces basically -> https://streamable.com/8joqc6

Oh got it!

**Review by Apandoh — APPROVED** [review]

**Pull request merged**
